AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - vendor/**/*
  RunRailsCops: true

AbcSize:
  Max: 20

ClassLength:
  Max: 100

CyclomaticComplexity:
  Max: 10

MethodLength:
  Max: 15
